version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: archllama-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: archllama

  redis:
    image: redis:7-alpine
    container_name: archllama-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: archllama-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongodb
      - redis
    volumes:
      - ../backend:/app
      - ../data:/data
      - ../models:/models
      - ../logs:/logs

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: archllama-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongodb_data:
  redis_data:
